### PR TITLE
Revert "Provide libsecret from shared modules for os_crypt"

### PR DESCRIPTION
**Pull request by AKoskovich**

### CODE REVIEW

**Comment by AKoskovich** [comment]
@bbhtt Related to this, is there a way I can trigger rebuilds for Slack if this gets merged without making a new commit to it's repo?

**Comment by bbhtt** [comment]
No you can't, until this update is published, which happens 4-5 hours after the build from merge commit is done.


The issue could be related to this https://gitlab.gnome.org/GNOME/libsecret/-/issues/49#note_1307164, you can try testing with gcrypt disabled.

IIRC, a lot of electron applications depend on the deprecated node-keytar module and that doesn't work well with this.

**Comment by AKoskovich** [comment]
> The issue could be related to this https://gitlab.gnome.org/GNOME/libsecret/-/issues/49#note_1307164, you can try testing with gcrypt disabled.

Tested with -Dcrypto=false, and the issue is no longer occurring. Is this an acceptable alternative to this revert, or is there something else that can be done?

**Comment by ZVNexus** [comment]
https://github.com/flathub/shared-modules/pull/295

**Comment by bbhtt** [comment]
No I suggest keeping it in, we already switched apps to using libsecret from baseapp. Apps that don't work can switch to disabling gcrypt.

The actual solution is of course for apps to switch to Electron's native keyring integration and for libsecret to fix the issue

**Pull request closed without merging**
