### PR TITLE
Provide libsecret from shared modules for os_crypt

### PR DESCRIPTION
**Pull request by AKoskovich**

### CODE REVIEW

**Comment by AKoskovich** [comment]
@bbhtt @TingPing Can you take a look at this? Also worth noting the Chromium base app already includes this: https://github.com/flathub/org.chromium.Chromium.BaseApp/blob/branch/23.08/org.chromium.Chromium.BaseApp.yaml#L8

**Comment by bbhtt** [comment]
Seems fine to me. There are quite a few applications adding it from the shared modules, they should be notified of the change

https://github.com/search?q=org%3Aflathub+org.electronjs.Electron2.BaseApp+libsecret.json&type=code&p=1

**Comment by AKoskovich** [comment]
> Seems fine to me. There are quite a few applications adding it from the shared modules, they should be notified of the change

What's the best way of going about  that, pinging them here or creating issues in each repo?

**Comment by bbhtt** [comment]
Probably by opening issues, (ones that are using 23.08 of the baseapp)

If you don't have the time, I can reach out later.

**Comment by AKoskovich** [comment]
> Probably by opening issues, (ones that are using 23.08 of the baseapp)

Done

**Pull request merged**
